
# Cursor size
env = XCURSOR_SIZE,20
env = HYPRCURSOR_SIZE,20

# Android SDK
env = ANDROID_HOME,/home/nacchofer31/Android/Sdk
env = ANDROID_SDK_ROOT,/home/nacchofer31/Android/Sdk
env = ANDROID_AVD_HOME,/home/nacchofer31/.config/.android/avd

# NVIDIA (Turing+ with GSP firmware)
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
